# Use postgres/example user/password credentials
version: '3.1'

services:

  go:
    build: .
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: test
      DB_NAME: account
      DB_PORT: 5432
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
